# Generated by Django 2.0.3 on 2018-04-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180417_2157'),
        ('catalog', '0004_auto_20180417_1728'),
    ]

    operations = [
    ]
