# Generated by Django 2.0.1 on 2018-05-01 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_merge_20180417_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Latitude for the venue', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Longitude for the venue', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='event',
            field=models.ForeignKey(help_text='select the event for this invitation', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Event'),
        ),
    ]
