# Generated by Django 2.0.3 on 2018-05-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_merge_20180417_2308'),
        ('catalog', '0005_merge_20180422_2331'),
    ]

    operations = [
    ]
