# Generated by Django 2.0.1 on 2018-05-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180501_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Longitude for the venue', max_digits=6, null=True),
        ),
    ]
