# Generated by Django 2.0.3 on 2018-05-01 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_merge_20180501_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='event',
            field=models.ForeignKey(help_text='select the event for this invitation', on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Event'),
        ),
    ]
