# Generated by Django 2.0.3 on 2018-04-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180403_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_mark_going', 'Set event as going'),)},
        ),
    ]
