# Generated by Django 2.0.1 on 2018-05-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180501_1454'),
        ('catalog', '0007_auto_20180501_1436'),
    ]

    operations = [
    ]
